### PR TITLE
feat: Add jupyterbook configuration

### PR DESCRIPTION
**Pull request by lsetiawan**
This PR adds jupyterbook configuration setup

### CODE REVIEW

**Comment by lsetiawan** [comment]
Preview of Jupyterbook can be found at https://snowexsql--92.org.readthedocs.build/en/92/ ... hopefully I did this right.

**Comment by jomey** [comment]
@micah-prime, @micahjohnson150 - How do you feel about using JupyterBook as the documentation framework. It's basically built on Sphinx and feels easier to contribute for newcomers.

Thoughts?

**Comment by micahjohnson150** [comment]
Looks good to me. Looks like the gallery thumbnails dont get rendered anymore. Is there a way to make the gallery still be dope little thumbnails? Here is what it was beforehand.


Screenshot 2024-07-25 at 9 35 16 AM

**Comment by lsetiawan** [comment]
@micahjohnson150 Unfortunately this is a feature that is missing from jupyter-book. See https://github.com/jupyter-book/jupyter-book/issues/1785 and https://github.com/jupyter-book/jupyter-book/issues/2036.

**Comment by jomey** [comment]
Thanks for pointing us to the Xarray examples.
Maybe this could be a Hackweek project task to organize our growing number of example tutorials :smile:

**Review by micah-prime — APPROVED** [review]

**Comment by JessicaS11** [comment]
> Unfortunately this is a feature that is missing from jupyter-book. See https://github.com/jupyter-book/jupyter-book/issues/1785 and https://github.com/jupyter-book/jupyter-book/issues/2036.

Not sure if this helps/is what you're after, but I did recently [add a gallery capability](https://github.com/ICESAT-2HackWeek/website-2024/commit/3bddb7a749824a03e2b1da411aa265a24ce9ed8a) (with user contributions via a `.yml` instead of the underlying panels) to the IS2 book.

**Pull request merged**
