### PR TITLE
GitHub - Add templates for feature and bug reports

### PR DESCRIPTION
**Pull request by jomey**
Edited the default template suggestions from GitHub

### CODE REVIEW

**Review by aaarendt — APPROVED** [review]
I'm looking at [this example bug report](https://gist.github.com/automationhacks/87b62440faf36d98ebbb732c372dd7c3) and they include space for a screenshot. Should we include that too?

**Comment by jomey** [comment]
> I'm looking at [this example bug report](https://gist.github.com/automationhacks/87b62440faf36d98ebbb732c372dd7c3) and they include space for a screenshot. Should we include that too?

This looks like the template that GitHub also first suggest when you start this process. I removed the sections for screenshots as I have personally never found them very useful. A copy of the actual code that causes it and the stracktrace has been most useful.

We could add some lines to encourage attaching a notebook.

Thoughts?

**Comment by aaarendt** [comment]
Sounds good, I trust your greater experience on this one. I'd say no to the notebook? Seems like the bug report forces people to be concise, whereas a notebook might promote dumping more code than is relevant to the problem?

**Comment by jomey** [comment]
> I'd say no to the notebook? Seems like the bug report forces people to be concise, whereas a notebook might promote dumping more code than is relevant to the problem?

Good point. Let's start with this and we can always revisit.

**Review by micah-prime — APPROVED** [review]
This looks great!

**Pull request merged**
