### PR TITLE
Issue #128 - Using campaign and site instead of site_name, site_id, p…

### PR DESCRIPTION
**Pull request by micah-prime**
Issue #128
Using campaign and site instead of site, site_id, pit_id

Now a campaign is the larger area like Grand Mesa
and a site is equivalent to a pit. So site.name is equivalent to pit_id

### CODE REVIEW

**Review by jomey — APPROVED** [review]
Just FYI:
I have a bigger PR coming with the restructure of ponits and image data. The changes to the API with this PR will probably have to get a close second look and a bit tricky to merge in. So maybe we can hold off on more PRs until I have that wrapped up (hopefully today)

**Comment by jomey** [comment]
Another thought is to wait with these changes and do them based off the re-worked coded base since they are smaller. Open to suggestions here

**Comment by micah-prime** [comment]
> #156

Sure! I will just rework this once that branch is merged

**Comment by micah-prime** [comment]
Closing in favor of https://github.com/SnowEx/snowexsql/pull/163

**Pull request closed without merging**
